---
services:
  mariadb:
    image: mariadb:11.3.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    ports:
      - "3306:3306"

  vault:
    image: hashicorp/vault:1.16.2
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
